services:
  clt-db:
    image: postgres:16-alpine
    container_name: clt-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-clt}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Paraguay2026}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-clt}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-clt
      dockerfile: Dockerfile
    container_name: clt-backend
    depends_on:
      clt-db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://clt-db:5432/${DB_NAME:-clt}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-Paraguay2026}
      JWT_SECRET: ${JWT_SECRET:-CltSecretKeyParaJWT256BitsMinimoParaSeguridadHS256MuyLarga}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:4200}
      # Correo y contraseña para restablecer contraseña (forgot-password)
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USER: ${MAIL_USER:-jhonathanjoel.bernal@gmail.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-iyqm jcph pmjo enzs}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend-clt
      dockerfile: Dockerfile
    container_name: clt-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres_data:
