export interface ListaMatrix {
        
        
        id: String,
        createdAt: String,
        id_OCRD: String,
        CardName: String,
        Id_Sup: String,
        Supervisora: String,
        Id_Usuario: String,
        Usuario: String,
        Lunes: String,
        Lunes_E: String,
        Lunes_S: String,
        Lunes_P: String,
        Martes: String,
        Martes_E: String,
        Martes_S: String,
        Martes_P: String,
        Miercoles: String,
        Miercoles_E:String,
        Miercoles_S: String,
        Miercoles_P:String,
        Jueves: String,
        Jueves_E: String,
        Jueves_S: String,
        Jueves_P: String,
        Viernes: String,
        Viernes_E: String,
        Viernes_S: String,
        Viernes_P: String,
        Sabado: String,
        Sabado_E: String,
        Sabado_S: String,
        Sabado_P: String,
        Domingo: String,
        Domingo_E: String,
        Domingo_S: String,
        Domingo_P: String,
        fechaInicio: string,
        fechaFin: string,
        idTipoAsignacion: String,
        nameTipoAsignacion: String
     }  